relative_links:
  enabled: true
  collections: true
include:
  - LINKS.md
  - https://gist.githubusercontent.com/Leandro-Sciola/d17d2a6ef5e49699f0ec1b737b2dbfb6/raw/a5f836c7226fde049d349aeb37df0e61dc0e6e9e/LINKS.md
